export default [
  {
    file: "nature.jpg",
    left: "50%",
    top: "25%",
    height: "40%",
    desc: "Cassie bein' cute while standing by a lake",
  },
  {
    file: "witch.jpg",
    left: "86%",
    top: "65%",
    height: "45%",
    desc: "Cassie bein' cute while wearing a witch costume",
  },
  {
    file: "hoodie.jpg",
    left: "15.5%",
    top: "25%",
    height: "25%",
    desc: "Cassie bein' cute while wearing an ears hoodie",
  },
  {
    file: "talkinghearts.jpg",
    left: "50%",
    top: "75%",
    height: "40%",
    desc: "Cassie bein' cute while sitting on a bed",
  },
  {
    file: "up.jpg",
    left: "84.5%",
    top: "25%",
    height: "25%",
    desc: "Cassie bein' cute while staring into space",
  },
  {
    file: "sparkles.webp",
    left: "14%",
    top: "65%",
    height: "45%",
    fallback: "sparkles.gif",
    desc: "Cassie bein' cute while wearing a cardboard crown",
  },
];
